export const routePath = {
    HOME: '/',
    SIGN_IN: '/sign-in',
    SIGN_UP: '/sign-up',
    ABOUT_US: '/about-us',
    SALE_CREATOR: '/sale-creator/:id',
    USER_PROFILE: '/user-profile',
    RESULT_SEARCH: '/result-search/:name',
    PRIVACY_POLICY: '/privacy-policy',
    BECOME_PARTNER: '/become-partner',
    DETAIL_PRODUCT: '/detail-product/:id',
    CONTACT: '/contacts',
    HELP: '/help',
    PAGE_NOT_FOUND: '*',
    MY_COUPONS: '/my-coupons',
    RECOVERY_PASSWORD: '/recovery-password',
    CHANGE_PASSWORD: '/change-password',
    CHANGE_NUMBER: '/change-number',
    FAVORITES: '/favorites',
    NEW_COUPONS: '/new-coupons'
}